function VisualizationGUI(net)
    % Create the main figure for the GUI
    fig = uifigure('Name', 'Driving Scenario Visualizer', 'Position', [300, 300, 400, 300]);

    % Set background color and customize the appearance
    fig.Color = [0.9, 0.9, 0.9]; % Light gray background

    % Create a title label for the GUI
    titleLabel = uilabel(fig, ...
        'Text', 'Select a Driving Scenario', ...
        'Position', [80, 230, 250, 30], ...
        'FontSize', 18, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center');

    % Create a vertical box layout for the buttons
    grid = uigridlayout(fig, [4, 1]);
    grid.RowHeight = {'1x', '1x', '1x', '1x'};
    grid.Padding = [10 10 10 10];
    grid.BackgroundColor = [0.9, 0.9, 0.9];

    % Add buttons for each scenario
    standardBtn = uibutton(grid, 'push', ...
        'Text', 'Standard Scenario', ...
        'FontSize', 16, ...
        'BackgroundColor', [0.2, 0.6, 0.8], ... % Light blue color
        'FontWeight', 'bold', ...
        'ButtonPushedFcn', @(btn, event) Visualization(net));

    complexPedestrianBtn = uibutton(grid, 'push', ...
        'Text', 'More Complex Pedestrian Scenario', ...
        'FontSize', 16, ...
        'BackgroundColor', [0.4, 0.7, 0.4], ... % Light green color
        'FontWeight', 'bold', ...
        'ButtonPushedFcn', @(btn, event) runComplexPedestrianScenario());

    swerveCarBtn = uibutton(grid, 'push', ...
        'Text', 'Frontal Car Swerving Scenario', ...
        'FontSize', 16, ...
        'BackgroundColor', [0.8, 0.4, 0.4], ... % Light red color
        'FontWeight', 'bold', ...
        'ButtonPushedFcn', @(btn, event) runSwerveCarScenario());

    dodgePedestrianBtn = uibutton(grid, 'push', ...
        'Text', 'Dodging Pedestrian Scenario', ...
        'FontSize', 16, ...
        'BackgroundColor', [0.9, 0.7, 0.2], ... % Yellow-orange color
        'FontWeight', 'bold', ...
        'ButtonPushedFcn', @(btn, event) DodgingVisualization(net));

    % Adjust button appearance and layout
    standardBtn.Layout.Row = 1;
    complexPedestrianBtn.Layout.Row = 2;
    swerveCarBtn.Layout.Row = 3;
    dodgePedestrianBtn.Layout.Row = 4;

    % Display the GUI
    movegui(fig, 'center');
end
